TAP version 14
# Subtest: support works standalone
    not ok 1 - fastify.someSupport is not a function
      ---
      stack: |
        Test.<anonymous> (test/plugins/environment.test.js:12:26)
      at:
        fileName: test/plugins/environment.test.js
        lineNumber: 12
        columnNumber: 26
        typeName: Test
        methodName: <anonymous>
        functionName: Test.<anonymous>
      type: TypeError
      tapCaught: returnedPromiseRejection
      source: |2
      
          await fastify.ready()
          const result = fastify.someSupport();
        -------------------------^
          console.log('=== result', result);
      ...
    
    1..1
not ok 1 - support works standalone # time=22.761ms
  ---
  at:
    fileName: test/plugins/environment.test.js
    lineNumber: 7
    columnNumber: 1
    typeName: Object
  source: |
    const environment = require('../../build/plugins/environment')
  
    test('support works standalone', async (t) => {
    ^
      const fastify = Fastify()
      fastify.register(environment)
  ...

1..1
